apiVersion: apps/v1
kind: Deployment
metadata:
  name: logs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logs-app
  template:
    metadata:
      labels:
        app: logs-app
    spec:
      containers:
        - name: logs-app
          image: library/logs:latest
          imagePullPolicy: IfNotPresent
